"""
Pydantic v2 schemas for Scenario API layer.
Read-only — scenarios are generated by agents, never created by clients.
"""
import uuid
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class ScenarioRead(BaseModel):
    """
    Single rerouting option — returned nested inside DisruptionRead.
    Three of these always exist per disruption (option_index 1, 2, 3).
    """

    model_config = {"from_attributes": True}

    id: uuid.UUID
    disruption_id: uuid.UUID
    option_index: int = Field(..., ge=1, le=3, description="Position: 1, 2, or 3")
    label: str = Field(..., description="Short option name e.g. 'Cape of Good Hope Route'")
    description: Optional[str] = None
    cost_delta_usd: Optional[float] = Field(
        default=None,
        description="Additional cost vs current route in USD. Positive = more expensive.",
    )
    time_delta_days: Optional[float] = Field(
        default=None,
        description="Additional transit days. Positive = slower.",
    )
    risk_score: Optional[float] = Field(
        default=None,
        ge=1.0,
        le=10.0,
        description="Risk exposure 1.0 (safe) to 10.0 (dangerous)",
    )
    composite_score: Optional[float] = Field(
        default=None,
        description="Weighted tradeoff score. Lower = better option.",
    )
    recommended: bool = Field(
        default=False,
        description="True for the top-ranked option only.",
    )
    created_at: datetime


class ScenarioList(BaseModel):
    """List of 3 scenarios for a disruption."""

    disruption_id: uuid.UUID
    scenarios: list[ScenarioRead]
    recommended_index: Optional[int] = Field(
        default=None,
        description="option_index of recommended scenario",
    )
